# Generated by Django 4.0.3 on 2022-05-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_is_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_feature',
            new_name='is_featured',
        ),
    ]
