# Generated by Django 4.0.3 on 2022-05-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='', max_length=400),
        ),
    ]
