# Generated by Django 4.0.3 on 2022-05-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_product_price_product_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAtribute',
            new_name='ProductAttribute',
        ),
    ]
