# Generated by Django 4.1.7 on 2023-03-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_productreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('Process', 'In Process'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='process', max_length=150),
        ),
    ]
